import Link from 'next/link';
import { ArrowUpRight,ArrowRight,BookOpen,Compass,Flame,Swords,Skull,UserRound,MapPin,Gem } from 'lucide-react';
import { db,view } from '@/lib/db';
import { SearchBox } from '@/components/shell';
import { EntryCard } from '@/components/entries';
import { JourneySummary } from '@/components/journey';
export const dynamic='force-dynamic';
export default async function Home() {
 const [total,base,dlc,groups,raw] = await Promise.all([db.entry.count(),db.entry.count({where:{content_type:'base_game'}}),db.entry.count({where:{content_type:'shadow_of_the_erdtree'}}),db.entry.groupBy({by:['category'],_count:true}),db.entry.findMany({where:{id:{in:['weapons-moonveil','weapons-bloodhound-s-fang','npcs-ranni-the-witch','talismans-green-turtle-talisman']}}})]);
 const counts=Object.fromEntries(groups.map(x=>[x.category,x._count]));
 const categories=[{id:'weapons',en:'ARMAMENTS',label:'무기',icon:Swords},{id:'bosses',en:'ADVERSARIES',label:'보스',icon:Skull},{id:'npcs',en:'CHARACTERS',label:'NPC',icon:UserRound},{id:'locations',en:'THE WORLD',label:'지역·던전',icon:MapPin},{id:'talismans',en:'TALISMANS',label:'탈리스만',icon:Gem}];
 return <div className="home-page">
  <section className="hero"><div className="hero-art" aria-hidden="true"><svg viewBox="0 0 500 500" fill="none"><defs><radialGradient id="halo"><stop stopColor="#b9a371" stopOpacity=".18"/><stop offset="1" stopColor="#b9a371" stopOpacity="0"/></radialGradient></defs><circle cx="260" cy="250" r="230" fill="url(#halo)"/><g stroke="#b9a371"><circle cx="260" cy="183" r="112"/><circle cx="204" cy="281" r="112"/><circle cx="316" cy="281" r="112"/><circle cx="260" cy="247" r="194" strokeOpacity=".15"/><circle cx="260" cy="247" r="201" strokeOpacity=".1"/><path d="M260 24v430m-108-343 108-48 108 48M129 395l131 63 131-63M129 198h262" strokeWidth="2"/><path d="M40 250h440M260 20v470" strokeOpacity=".08"/></g></svg></div>
   <div className="hero-copy"><div className="eyebrow hero-eyebrow"><span/> THE TARNISHED’S COMPANION</div><h1>ELDEN RING<span>ARCHIVE</span></h1><p className="hero-korean">빛바랜 자의 여정, 당신만의 기록.</p><p className="hero-description">틈새의 땅부터 그림자의 땅까지.<br/>흩어진 지식을 연결하고, 다음 여정을 준비하세요.</p><div className="hero-pills"><span><i/>ELDEN RING 본편</span><span><i/>SHADOW OF THE ERDTREE</span></div></div><div className="hero-index">01 — PERSONAL KNOWLEDGE</div>
  </section>
  <section className="search-section"><SearchBox large/><div className="search-hints"><span>빠른 검색</span>{[['명도 월은','Moonveil'],['라니','라니'],['메스메르','Messmer'],['쌍두 거북','Two-Headed Turtle']].map(([label,q])=><Link key={q} href={`/search?q=${encodeURIComponent(q)}`}>{label}<ArrowUpRight size={11}/></Link>)}<small>한국어 · ENGLISH</small></div></section>
  <div className="archive-stats"><div><BookOpen size={18}/><strong>{total.toLocaleString()}</strong><span>전체 문서</span></div><div><Compass size={18}/><strong>{base.toLocaleString()}</strong><span>본편 기록</span></div><div><Flame size={18}/><strong>{dlc.toLocaleString()}</strong><span>그림자의 땅</span></div><Link href="/about">데이터 수집 현황 <ArrowUpRight size={16}/></Link></div>
  <section className="section"><div className="section-heading"><div><span className="eyebrow">EXPLORE THE ARCHIVE</span><h2>무엇을 찾고 있나요?</h2></div><Link href="/search">전체 문서 탐색 <ArrowRight size={16}/></Link></div><div className="category-grid">{categories.map(({id,en,label,icon:Icon},i)=><Link className="category-tile" key={id} href={`/browse/${id}`}><span className="tile-number">0{i+1}</span><Icon size={32} strokeWidth={1.1}/><small>{en}</small><h3>{label}</h3><div><span>{counts[id]??0} 문서</span><ArrowUpRight size={18}/></div></Link>)}</div></section>
  <div className="home-lower"><section className="section featured-section"><div className="section-heading"><div><span className="eyebrow">A PLACE TO BEGIN</span><h2>여정에 도움이 되는 기록</h2></div><Link href="/search?review=true">탐색 <ArrowUpRight size={16}/></Link></div><div className="featured-grid">{raw.map(e=><EntryCard key={e.id} entry={view(e)}/>)}</div></section><aside className="journey-column"><JourneySummary/><Link href="/browse/progression" className="journey-tip"><span className="eyebrow">FIRST JOURNEY</span><Compass size={30} strokeWidth={1}/><h3>어디로 가야 할지<br/>막막한 당신에게.</h3><p>진행 가이드에서 다음 목적지를 찾아보세요.</p><span className="text-button">진행 가이드 <ArrowUpRight size={15}/></span></Link></aside></div>
  <Link href="/search?content=shadow_of_the_erdtree" className="dlc-banner"><div className="banner-symbol"><Flame size={42} strokeWidth={1}/></div><div><span className="eyebrow">BEYOND THE LANDS BETWEEN</span><h2>그림자의 땅으로</h2><p>새로운 무기, 인물, 그리고 아직 끝나지 않은 이야기.</p></div><span>Shadow of the Erdtree <ArrowUpRight size={22}/></span></Link>
 </div>;
}
