'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft,ArrowRight,Search,LayoutGrid,ListFilter } from 'lucide-react';
import { CATEGORIES,type EntryView } from '@/lib/catalog';
import { EntryCard } from './entries';
export function Browser({initialCategory='',initialQuery='',initialContent='',initialReview=false}:{initialCategory?:string;initialQuery?:string;initialContent?:string;initialReview?:boolean}) {
 const router=useRouter();const [q,setQ]=useState(initialQuery),[category,setCategory]=useState(initialCategory),[content,setContent]=useState(initialContent),[review,setReview]=useState(initialReview),[page,setPage]=useState(1),[subtype,setSubtype]=useState('');
 const [data,setData]=useState<{entries:EntryView[];total:number;pages:number}>({entries:[],total:0,pages:0}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{setQ(initialQuery);setCategory(initialCategory);setContent(initialContent);setReview(initialReview);setPage(1);setSubtype('');},[initialCategory,initialQuery,initialContent,initialReview]);
 useEffect(()=>{setPage(1);},[q,category,content,review,subtype]);
 useEffect(()=>{
  const abort=new AbortController();setLoading(true);setError('');
  const params=new URLSearchParams({q,category,content,page:String(page),review:String(review),subtype});
  const timer=setTimeout(()=>{fetch(`/api/entries?${params}`,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('검색 요청 실패');return r.json();}).then(d=>{setData(d);setLoading(false);}).catch(e=>{if(e.name!=='AbortError'){setError('문서를 불러오지 못했습니다. 서버 연결을 확인하세요.');setLoading(false);}});},180);
  return()=>{clearTimeout(timer);abort.abort();};
 },[q,category,content,page,review,subtype]);
 const title=initialCategory?CATEGORIES[initialCategory as keyof typeof CATEGORIES]:'전체 문서 검색';
 return <div className="content-page"><div className="page-heading"><span className="eyebrow">ARCHIVE / EXPLORE</span><h1>{title}</h1><p>한국어와 영어로 검색하고, 서로 연결된 정보를 찾아보세요.</p></div><div className="browse-search"><Search size={20}/><input aria-label="문서 검색" value={q} onChange={e=>setQ(e.target.value)} placeholder="이름, 획득 장소, 태그로 검색…"/><span>KO / EN</span></div><div className="filter-bar"><div className="segmented" aria-label="본편 DLC 필터">{[['','전체'],['base_game','본편'],['shadow_of_the_erdtree','Shadow of the Erdtree']].map(([v,l])=><button aria-pressed={content===v} className={content===v?'selected':''} key={v} onClick={()=>setContent(v)}>{l}</button>)}</div><div className="filter-selects"><ListFilter size={16}/><select aria-label="카테고리 필터" value={category} onChange={e=>{setCategory(e.target.value);setSubtype('');}}><option value="">전체 카테고리</option>{Object.entries(CATEGORIES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{category==='locations'&&<select aria-label="지역 세부 분류" value={subtype} onChange={e=>setSubtype(e.target.value)}><option value="">모든 장소</option>{['주요 지역','레거시 던전','던전','지하묘지','동굴','갱도','봉인감옥','장소'].map(s=><option key={s}>{s}</option>)}</select>}<label className="review-filter"><input type="checkbox" checked={review} onChange={e=>setReview(e.target.checked)}/> 검토 필요</label></div></div><div className="results-label"><span>{loading?'검색 중…':`${data.total.toLocaleString()}개 문서`}{q&&` · “${q}”`}</span><LayoutGrid size={15}/></div>{error?<p className="error-box" role="alert">{error}</p>:loading?<div className="entry-grid skeleton-grid" aria-label="검색 중">{[1,2,3,4,5,6].map(i=><div key={i} className="skeleton"/>)}</div>:data.entries.length?<div className="entry-grid">{data.entries.map(e=><EntryCard key={e.id} entry={e}/>)}</div>:<div className="empty-state"><Search size={36}/><h2>검색 결과가 없습니다</h2><p>다른 이름을 검색하거나 필터를 변경해 보세요. 아직 수집되지 않은 자료는 관리자에서 추가할 수 있습니다.</p><button className="button" onClick={()=>{setQ('');setCategory('');setContent('');setSubtype('');setReview(false);router.replace('/search');}}>필터 초기화</button></div>}{!loading&&data.pages>1&&<div className="pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ArrowLeft size={16}/> 이전</button><span>{page} / {data.pages}</span><button disabled={page>=data.pages} onClick={()=>setPage(p=>p+1)}>다음 <ArrowRight size={16}/></button></div>}</div>;
}
