'use client';
import { useEffect,useState } from 'react';
import { Save,Trash2,Plus,Download } from 'lucide-react';
import { useLibrary } from './library';
import { SpoilerGuard } from './entries';
import { useProfile } from './storage';
type Build={id:string;name:string;level:number;stats:Record<string,number>;equipment:Record<string,string|string[]>};
const stats={vigor:60,mind:20,endurance:30,str:20,dex:40,int:10,fai:10,arc:39};
const labels:Record<string,string>={vigor:'생명력',mind:'정신력',endurance:'지구력',str:'근력',dex:'기량',int:'지력',fai:'신앙',arc:'신비'};
const fresh=():Build=>({id:crypto.randomUUID(),name:'새 빌드',level:150,stats:{...stats},equipment:{}});
export function Builds(){
 const {entries,error}=useLibrary(),{profile}=useProfile();const [all,setAll]=useState<Build[]>([]),[current,setCurrent]=useState<Build|null>(null),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('elden-ring-builds:v1')??'[]');if(Array.isArray(x))setAll(x);}catch{setNotice('저장된 빌드를 읽지 못했습니다.');}setCurrent(fresh());setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('elden-ring-builds:v1',JSON.stringify(all));}catch{setNotice('빌드를 브라우저에 저장하지 못했습니다. 내보내기로 보관하세요.');}},[all,ready]);
 if(!current)return <p className="content-page">빌드 노트 준비 중…</p>;
 const c=current;
 const slots=[['right','오른손 무기','weapons',false],['left','왼손 무기·방패','weapons,shields',false],['armor','방어구','armor',true],['talismans','탈리스만 (최대 4)','talismans',true],['sorceries','마술','sorceries',true],['incantations','기도','incantations',true]] as const;
 return <div className="content-page"><div className="page-heading"><span className="eyebrow">PLAN YOUR NEXT BATTLE</span><h1>빌드 노트</h1><p>장비와 능력치를 보관하는 개인 노트입니다. 데미지·중량·요구 스탯을 자동 계산하지 않습니다.</p></div><div className="build-layout"><aside className="build-list"><button className="button" onClick={()=>setCurrent(fresh())}><Plus size={15}/>새 빌드</button>{all.map(b=><button key={b.id} className={b.id===c.id?'selected':''} onClick={()=>setCurrent(b)}><strong>{b.name}</strong><small>Lv. {b.level}</small></button>)}</aside><section className="build-editor"><div className="form-grid"><label>빌드 이름<input value={c.name} onChange={e=>setCurrent({...c,name:e.target.value})}/></label><label>레벨<input type="number" min={1} max={713} value={c.level} onChange={e=>setCurrent({...c,level:Number(e.target.value)})}/></label></div><h2>능력치</h2><div className="build-stats">{Object.entries(labels).map(([k,l])=><label key={k}>{l}<input type="number" min={1} max={99} value={c.stats[k]} onChange={e=>setCurrent({...c,stats:{...c.stats,[k]:Number(e.target.value)}})}/></label>)}</div><p className="muted">기본 직업은 모델링하지 않으므로 스탯 합과 레벨의 일치 여부는 직접 확인하세요.</p><h2>장비·마법</h2>{error&&<p className="error-box">{error}</p>}<div className="form-grid">{slots.map(([key,label,categories,multiple])=><label key={key}>{label}<select multiple={multiple} value={c.equipment[key]??(multiple?[]:'')} onChange={e=>setCurrent({...c,equipment:{...c.equipment,[key]:multiple?Array.from(e.target.selectedOptions).map(o=>o.value):e.target.value}})}>{!multiple&&<option value="">선택 안 함</option>}{entries.filter(e=>categories.split(',').includes(e.category)&&(!profile.hideSpoilers||!e.spoiler)).map(e=><option key={e.id} value={e.id}>{e.nameKo} {e.content_type==='base_game'?'':'[DLC]'}</option>)}</select>{multiple&&<small>Ctrl / Command 또는 모바일 선택창에서 여러 개 선택</small>}</label>)}</div><div className="editor-actions"><button className="button" onClick={()=>{if(!c.name.trim()||c.level<1||c.level>713||Object.values(c.stats).some(x=>!Number.isInteger(x)||x<1||x>99)){setNotice('이름·레벨·능력치 범위를 확인하세요.');return;}if(Array.isArray(c.equipment.talismans)&&c.equipment.talismans.length>4){setNotice('탈리스만은 4개까지 선택할 수 있습니다.');return;}setAll(a=>[...a.filter(b=>b.id!==c.id),c]);setNotice('빌드를 저장했습니다.');}}><Save size={15}/>빌드 저장</button><button className="text-button danger" onClick={()=>{setAll(a=>a.filter(b=>b.id!==c.id));setCurrent(fresh());setNotice('선택한 빌드를 목록에서 삭제했습니다.');}}><Trash2 size={15}/>목록에서 삭제</button><button className="text-button" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(all,null,2)],{type:'application/json'}));a.download='elden-ring-builds.json';a.click();URL.revokeObjectURL(a.href);}}><Download size={15}/>내보내기</button></div>{notice&&<p role="status" className="notice-box">{notice}</p>}</section></div></div>;
}
