'use client';
import Link from 'next/link';
import {ArchiveImage} from './archive-image';
import { ArrowLeft,ArrowUpRight,FilePenLine,Link2,BookOpen,Check,ExternalLink } from 'lucide-react';
import { CATEGORIES,FIELD_LABELS,type EntryView } from '@/lib/catalog';
import { Badge,CheckButton,EntryIcon,FavoriteButton,SpoilerGuard } from './entries';
import { useProfile } from './storage';
type Related={id:string;nameKo:string;nameEn:string;category:string;content_type:string;spoiler:boolean;label:string;direction:string};
export type StepView={id:string;title:string;position:number;locationId:string|null;npcId:string|null;requiredItems:string[];prerequisites:string;failure:string;nextStepId:string|null;spoiler:boolean};
type Source={title:string;url:string;note:string;checkedAt:string|null};
const expected:Record<string,string[]>={weapons:['weight','requirements','scaling','attack','defence','skill','upgrade','maxUpgrade','damageType','effect'],bosses:['region','location','required','hp','resistance','weakness','parry','spiritSummon','npcSummon','runes','drops','phases','tips'],npcs:['location','route','role','consequences'],locations:['level','weaponLevel','mapFragment','goldenSeeds','sacredTears'],armor:['set','part','weight','damageNegation','resistance','effect'],talismans:['weight','effect','variants'],sorceries:['fpCost','staminaCost','slots','requirements','effect','chargeable'],incantations:['fpCost','staminaCost','slots','requirements','effect','chargeable']};
export function Detail({entry:e,assetId,locationImages,related,sources,steps,upgrades}:{entry:EntryView;assetId?:string;locationImages:{id:string;nameKo:string;source:string}[];related:Related[];sources:Source[];steps:StepView[];upgrades:{level:number;affinity:string;attack:Record<string,unknown>;scaling:Record<string,unknown>}[]}) {
 const {profile,note}=useProfile();
 const keys=[...new Set([...(expected[e.category]??[]),...Object.keys(e.details).filter(k=>!['assetId','locationPictures'].includes(k))])];
 return <div className="content-page detail-page"><Link href={`/browse/${e.category}`} className="back-link"><ArrowLeft size={14}/>{CATEGORIES[e.category as keyof typeof CATEGORIES]} 목록</Link><SpoilerGuard key={e.id} spoiler={e.spoiler}><header className="document-header"><span className="document-icon"><EntryIcon category={e.category} size={41}/></span><div><div className="document-meta"><Badge content={e.content_type}/><span>{CATEGORIES[e.category as keyof typeof CATEGORIES]}{e.subtype&&` · ${e.subtype}`}</span></div><h1>{e.nameKo}</h1><p>{e.nameEn}</p></div><div className="document-actions"><FavoriteButton id={e.id}/><CheckButton id={e.id}/></div></header>
 <div className="document-notice"><BookOpen size={17}/><span>{e.verification_status==='verified'?'검증 완료된 문서입니다.':'검토 필요 · 현재 패치 또는 독립 출처와 교차 확인되지 않은 정보가 포함되어 있습니다.'}{e.translationPending&&' 한국어 공식 명칭이 아직 등록되지 않았습니다.'} 미등록 수치는 임의로 추정하지 않습니다.</span><Link href={`/admin?id=${e.id}`}>수정 <FilePenLine size={13}/></Link></div>
 {e.summary&&<p className="document-summary">{e.summary}</p>}<div className="document-layout"><div className="document-main"><section className="document-section"><h2>기본 정보 <span>INFORMATION</span></h2><div className="fact-table">{keys.map(key=><div className="fact-row" key={key}><div className="fact-label">{FIELD_LABELS[key]??key}</div><div className="fact-value"><SpoilerGuard spoiler={e.category==='npcs' && ['route','consequences'].includes(key)} compact><Value value={e.details[key]}/></SpoilerGuard></div></div>)}</div></section>
 <section className="document-section"><h2>획득 방법·위치 <span>WHERE TO FIND</span></h2><p className="acquisition-box"><span><EntryIcon category="locations" size={19}/></span>{e.acquisition||'아직 조사되지 않았습니다. 출처를 확인하고 획득 정보를 추가해 주세요.'}</p></section>
 {locationImages.length>0&&<section className="document-section"><h2>위치 참고 그림 <span>ROUTE PICTURES</span></h2><p className="muted">블로그 작성자의 위치 그림입니다. 클릭해 확대하고, 아래 출처에서 공략 맥락을 확인하세요.</p><div className="route-gallery">{locationImages.map(a=><figure key={a.id}><figcaption>{a.nameKo}</figcaption><ArchiveImage assetId={a.id} name={a.nameKo} source={a.source}/></figure>)}</div></section>}
 {steps.length>0&&<section className="document-section"><h2>퀘스트 단계 <span>QUEST PROGRESS</span></h2><p className="muted">{steps.filter(s=>profile.checked.includes(s.id)).length} / {steps.length} 단계 완료 · 현재 캐릭터의 진행만 기록합니다.</p><div className="quest-steps">{steps.map(s=><div className="quest-step" key={s.id}><span className="step-number">{String(s.position).padStart(2,'0')}</span><SpoilerGuard spoiler={s.spoiler}><div className="step-content"><div className="step-heading"><h3>{s.title}</h3><CheckButton id={s.id} label="단계 완료"/></div><p>{s.prerequisites}</p><div className="step-links">{[s.locationId,s.npcId,...s.requiredItems].filter(Boolean).map((id,i)=>{const r=related.find(r=>r.id===id);return <Link key={`${id}-${i}`} href={`/entry/${id}`}>{r?.nameKo??id}<ArrowUpRight size={12}/></Link>;})}</div><p className="step-warning">주의: {s.failure||'확인된 실패 조건 없음'}</p>{s.nextStepId&&<small className="muted">다음 단계: {steps.find(t=>t.id===s.nextStepId)?.position}</small>}</div></SpoilerGuard></div>)}</div></section>}
 {upgrades.length>0&&<section className="document-section"><h2>강화 단계별 수치</h2><div className="upgrade-table"><table><thead><tr><th>단계</th><th>변질</th><th>공격력</th><th>보정</th></tr></thead><tbody>{upgrades.map(u=><tr key={`${u.level}-${u.affinity}`}><td>+{u.level}</td><td>{u.affinity}</td><td><Value value={u.attack}/></td><td><Value value={u.scaling}/></td></tr>)}</tbody></table></div></section>}
 <section className="document-section"><h2>나의 메모 <span>PERSONAL NOTES</span></h2><textarea className="note-editor" aria-label="나의 메모" placeholder="공략 기록, 다음 목표, 놓치지 않을 것…" value={profile.notes[e.id]??''} onChange={ev=>note(e.id,ev.target.value)}/><small className="muted">이 브라우저에 자동 저장됩니다. 데이터 편집과 별도로 보관합니다.</small></section>
 <section className="document-section sources-section"><h2>출처·검증 <span>SOURCES</span></h2>{sources.length?sources.map(s=><div className="source-row" key={s.url}><ExternalLink size={15}/><div><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title}<ArrowUpRight size={12}/></a><p>{s.note}</p><small>{s.checkedAt?`출처 확인: ${new Date(s.checkedAt).toLocaleDateString('ko-KR')}`:'교차 확인 미완료'}</small></div></div>):<p className="muted">등록된 출처가 없습니다. 검증 전 자료로 취급하세요.</p>}</section></div>
 <aside className="related-sidebar"><h2><Link2 size={17}/> 연결된 기록 <span>{related.length}</span></h2>{related.length?related.map((r,i)=><SpoilerGuard key={`${r.id}-${r.label}-${i}`} spoiler={r.spoiler || (e.category==='quests' && ['보상','퀘스트 경유지'].includes(r.label))} compact><Link className="related-link" href={`/entry/${r.id}`}><small>{r.direction==='incoming'?'이 문서와 연결':r.label}</small><strong>{r.nameKo}</strong><span>{r.nameEn}<ArrowUpRight size={13}/></span><Badge content={r.content_type}/></Link></SpoilerGuard>):<p className="muted">연결 문서가 아직 없습니다. 편집 화면에서 관계를 추가할 수 있습니다.</p>}<ArchiveImage assetId={assetId} name={e.nameKo} source={e.imageSource}/><Link className="back-link" href="/map">지도와 위치 기록 보기 ↗</Link></aside></div></SpoilerGuard></div>;
}
function Value({value}:{value:unknown}) {
 if(value===undefined||value===null||value==='')return <span className="unknown">미등록 · 확인 필요</span>;
 if(typeof value==='boolean')return <span>{value?'가능 / 해당':'불가 / 해당 없음'}</span>;
 if(Array.isArray(value))return <div className="value-list">{value.map((v,i)=><span key={i}><Value value={v}/></span>)}</div>;
 if(typeof value==='object')return <div className="stat-grid">{Object.entries(value).map(([k,v])=><div key={k}><span>{FIELD_LABELS[k]??k}</span><strong><Value value={v}/></strong></div>)}</div>;
 return <span>{String(value)}</span>;
}
