'use client';
import { useEffect,useState } from 'react';
import { Download,Upload,Star,CheckSquare,ArrowUpRight } from 'lucide-react';
import { CATEGORIES,type EntryView } from '@/lib/catalog';
import { EntryCard,CheckButton,SpoilerGuard,Badge } from './entries';
import { useProfile } from './storage';
import Link from 'next/link';
export function useLibrary(){const [entries,setEntries]=useState<EntryView[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{const abort=new AbortController();fetch('/api/library',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>{setEntries(d.entries);setLoading(false);}).catch(e=>{if(e.name!=='AbortError'){setError('데이터를 불러올 수 없습니다.');setLoading(false);}});return()=>abort.abort();},[]);return {entries,loading,error};}
export function Library({mode}:{mode:'favorites'|'checklist'}) {
 const {entries,loading,error}=useLibrary(),{profile,replace}=useProfile();const [category,setCategory]=useState(''),[content,setContent]=useState(''),[q,setQ]=useState(''),[page,setPage]=useState(1),[notice,setNotice]=useState('');
 const candidates=entries.filter(e=>mode==='favorites'?profile.favorites.includes(e.id):['bosses','graces','quests','locations','weapons','talismans','sorceries','incantations','spirits','items'].includes(e.category));
 const filtered=candidates.filter(e=>(!category||e.category===category)&&(!content||e.content_type===content)&&(!q||`${e.nameKo} ${e.nameEn}`.toLowerCase().includes(q.toLowerCase())));
 const done=filtered.filter(e=>profile.checked.includes(e.id)).length;
 const percent=filtered.length?Math.round(done/filtered.length*100):0;
 useEffect(()=>setPage(1),[category,content,q]);
 function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,profile},null,2)],{type:'application/json'}));a.download='elden-ring-journey.json';a.click();URL.revokeObjectURL(a.href);}
 async function importData(file:File){try{const d=JSON.parse(await file.text());if(d.version!==1||!d.profile||!Array.isArray(d.profile.favorites)||!Array.isArray(d.profile.checked)||!d.profile.favorites.every((x:unknown)=>typeof x==='string')||!d.profile.checked.every((x:unknown)=>typeof x==='string')||typeof d.profile.hideSpoilers!=='boolean'||typeof d.profile.notes!=='object'||d.profile.notes===null||!Object.values(d.profile.notes).every(x=>typeof x==='string'))throw new Error();replace(d.profile);setNotice('진행 데이터를 복원했습니다.');}catch{setNotice('가져오기 실패: 올바른 v1 진행 데이터 JSON을 선택하세요.');}}
 return <div className="content-page"><div className="page-heading"><span className="eyebrow">YOUR PERSONAL JOURNEY</span><h1>{mode==='favorites'?'내 즐겨찾기':'플레이 체크리스트'}</h1><p>{mode==='favorites'?'다시 찾아보고 싶은 기록을 한곳에.':'보스, 축복, 퀘스트, 장비와 던전의 진행을 기록하세요.'}</p></div>{mode==='checklist'&&<div className="progress-panel"><div><CheckSquare size={26}/><span>현재 목록 진행률</span><strong>{percent}%</strong><small>{done} / {filtered.length} 완료</small></div><div className="progress-track"><i style={{width:`${percent}%`}}/></div><p>수집된 문서 중 현재 필터의 완료 비율입니다. 게임 전체 달성률이 아닙니다. 퀘스트 단계 체크는 상세 문서에서 따로 관리합니다.</p></div>}<div className="filter-bar"><input className="field" aria-label="목록 검색" placeholder="목록 내 검색" value={q} onChange={e=>setQ(e.target.value)}/><select className="field" aria-label="카테고리" value={category} onChange={e=>setCategory(e.target.value)}><option value="">전체 카테고리</option>{Object.entries(CATEGORIES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select className="field" aria-label="콘텐츠" value={content} onChange={e=>setContent(e.target.value)}><option value="">전체</option><option value="base_game">본편</option><option value="shadow_of_the_erdtree">Shadow of the Erdtree</option></select></div><div className="results-label"><span>{filtered.length}개의 기록</span><div className="backup-actions"><button onClick={exportData}><Download size={14}/> 진행 내보내기</button><label><Upload size={14}/> 가져오기<input type="file" accept="application/json" onChange={e=>{if(e.target.files?.[0])void importData(e.target.files[0]);e.target.value='';}}/></label></div></div>{notice&&<p role="status" className="notice-box">{notice}</p>}{loading?<p className="muted">불러오는 중…</p>:error?<p role="alert" className="error-box">{error}</p>:!filtered.length?<div className="empty-state"><Star size={35}/><h2>{mode==='favorites'?'아직 저장한 문서가 없습니다':'해당하는 기록이 없습니다'}</h2><p>문서의 별 버튼을 누르거나 필터를 변경해 보세요.</p><Link className="button" href="/search">문서 탐색 <ArrowUpRight size={16}/></Link></div>:mode==='favorites'?<div className="entry-grid">{filtered.slice((page-1)*24,page*24).map(e=><EntryCard key={e.id} entry={e}/>)}</div>:<div className="checklist-list">{filtered.slice((page-1)*40,page*40).map(e=><div className="checklist-row" key={e.id}><SpoilerGuard spoiler={e.spoiler} compact><Link href={`/entry/${e.id}`}><strong>{e.nameKo}</strong><small>{e.nameEn}</small></Link><span className="checklist-category">{CATEGORIES[e.category as keyof typeof CATEGORIES]}</span><Badge content={e.content_type}/><CheckButton id={e.id} label={e.category==='bosses'?'처치':e.category==='locations'?'탐험':e.category==='quests'?'퀘스트 완료':'획득·발견'}/></SpoilerGuard></div>)}</div>}{filtered.length>(mode==='favorites'?24:40)&&<div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>이전</button><span>{page} / {Math.ceil(filtered.length/(mode==='favorites'?24:40))}</span><button disabled={page>=Math.ceil(filtered.length/(mode==='favorites'?24:40))} onClick={()=>setPage(p=>p+1)}>다음</button></div>}</div>;
}
