import fs from 'node:fs';import crypto from 'node:crypto';import * as cheerio from 'cheerio';import robotsParser from 'robots-parser';import {fetch,EnvHttpProxyAgent} from 'undici';import {buildDataset} from './dataset';import {assertAllowed,excluded} from '../lib/validation';
const ua='ChatGPT-User; personal Elden Ring reference archive',agent=new EnvHttpProxyAgent(),rules=new Map<string,ReturnType<typeof robotsParser>>(),last=new Map<string,number>(),entries=buildDataset();
async function get(url:string){const u=new URL(url);if(!['intensity.tistory.com','travous.tistory.com'].includes(u.hostname))throw Error('Unapproved blog');if(!rules.has(u.origin)){const r=await fetch(u.origin+'/robots.txt',{dispatcher:agent,headers:{'User-Agent':ua}});if(!r.ok)throw Error('robots unavailable');rules.set(u.origin,robotsParser(u.origin+'/robots.txt',await r.text()));}if(rules.get(u.origin)!.isAllowed(url,'ChatGPT-User')===false)throw Error('robots denied');const delay=Math.max(0,1500-(Date.now()-(last.get(u.origin)??0)));if(delay)await new Promise(r=>setTimeout(r,delay));last.set(u.origin,Date.now());const r=await fetch(url,{dispatcher:agent,headers:{'User-Agent':ua},signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('HTTP '+r.status);return r.text();}
const assets=JSON.parse(fs.readFileSync('data/assets.json','utf8')),rows:any[]=fs.existsSync('data/enrichment/blogs.json')?JSON.parse(fs.readFileSync('data/enrichment/blogs.json','utf8')):[],report:any[]=[];
for(const [host,path] of [['intensity.tistory.com','/category/게임/엘든링'],['travous.tistory.com','/category/PC/엘든 링']]){
 const pages=new Map<string,string>();
 for(let page=1;page<=3;page++){const url='https://'+host+encodeURI(path)+`?page=${page}`;try{const $=cheerio.load(await get(url));$('a[href]').each((_,a)=>{const href=$(a).attr('href')??'',text=$(a).text().trim(),title=text.split('\n')[0].trim();if(/^\/\d+$/.test(href)&&/위치|가는 법|획득|공략/.test(title)&&!excluded.test(text)&&!/펌\s*금지|재가공\s*금지|보호되어/.test(text))pages.set('https://'+host+href,title);});}catch(e){report.push({url,error:String(e)});break;}}
 for(const [url,listedTitle] of [...pages].slice(0,16)){try{const $=cheerio.load(await get(url)),body=$('.contents_style,.tt_article_useless_p_margin').first();if(!body.length)throw Error('Article body missing');const text=body.text();if(excluded.test(text)||/펌\s*금지|무단[^\n]{0,10}(전재|복제|사용)|재가공\s*금지/.test(text)){report.push({url,status:'excluded scope or author restriction'});continue;}const title=$('meta[property="og:title"]').attr('content')??listedTitle;const compact=(s:string)=>s.replace(/[\s,·+]/g,'');const matches=entries.filter(e=>!e.translationPending&&e.nameKo.length>=4&&compact(title).includes(compact(e.nameKo))).sort((a,b)=>b.nameKo.length-a.nameKo.length);let entry=matches[0];if(title.includes('안개 계곡의 요새'))entry={id:'locations-fog-rift-fort',nameKo:'안개 계곡의 요새',nameEn:'Fog Rift Fort',category:'locations',content_type:'shadow_of_the_erdtree',spoiler:false} as typeof entries[number];if(title.replace(/\s/g,'').includes('황금나무의은총+2'))entry={id:'talismans-erdtrees-favor-2',nameKo:'황금 나무의 은총 +2',nameEn:"Erdtree's Favor +2",category:'talismans',content_type:'base_game',spoiler:true} as typeof entries[number];const published=$('meta[property="article:published_time"]').attr('content')??$('time').first().attr('datetime')??'';const dlc=/dlc|그림자의 땅|황금나무의 그림자/i.test(title)||entry?.content_type==='shadow_of_the_erdtree';if(!entry&&!dlc&&host==='intensity.tistory.com'){report.push({url,status:'scope needs review; skipped'});continue;}
 const ids:string[]=[];body.find('img').each((i,img)=>{const src=$(img).attr('src')??$(img).attr('data-src');if(!src)return;const u=new URL(src,url);if(!['blog.kakaocdn.net','t1.daumcdn.net'].includes(u.hostname)||/\.gif$/i.test(u.pathname))return;const id='asset-'+crypto.createHash('sha256').update(u.href).digest('hex').slice(0,32);const raw={id,url:u.href,source:url,kind:'route',nameKo:title+` · 위치 그림 ${i+1}`,entryId:entry?.id,category:entry?.category??'locations',content_type:dlc?'shadow_of_the_erdtree':'base_game',spoiler:entry?.spoiler??true,rights:'블로그의 게임 화면/공략 이미지. 작성자 원본에 귀속. 개인용 로컬 참조 캐시이며 재배포 허가 미확인.'};assertAllowed(raw);assets.push(raw);ids.push(id);});
 if(entry&&ids.length){rows.push({spoiler:entry.spoiler,id:entry.id,nameKo:entry.nameKo,nameEn:entry.nameEn,category:entry.category,content_type:entry.content_type,details:{locationPictures:ids},sources:[{title:title.slice(0,190),url,checkedAt:new Date().toISOString(),note:'개인 참조용 위치 그림 출처. 공략 본문 복사 없음. 블로그 단독 정보는 검토 필요.'}]});}report.push({url,title,status:'ok',images:ids.length,published});console.log(title,ids.length);
 }catch(e){report.push({url,error:String(e)});if(String(e).includes('403')||String(e).includes('429'))break;}}
}
const merged=new Map<string,any>();for(const row of rows){const previous=merged.get(row.id);merged.set(row.id,{...previous,...row,details:{...previous?.details,...row.details,locationPictures:[...new Set([...(previous?.details.locationPictures??[]),...(row.details.locationPictures??[])])]},sources:[...new Map([...(previous?.sources??[]),...row.sources].map((s:any)=>[s.url,s])).values()]});}
fs.writeFileSync('data/assets.json',JSON.stringify([...new Map(assets.map((r:any)=>[r.id,r])).values()],null,2)+'\n');fs.writeFileSync('data/enrichment/blogs.json',JSON.stringify([...merged.values()],null,2)+'\n');fs.writeFileSync('data/enrichment/blogs-report.json',JSON.stringify(report,null,2)+'\n');await agent.destroy();
