import fs from 'node:fs';import crypto from 'node:crypto';import * as cheerio from 'cheerio';import {fetch,EnvHttpProxyAgent} from 'undici';import robotsParser from 'robots-parser';import {buildDataset} from './dataset';import {assertAllowed} from '../lib/validation';
const agent=new EnvHttpProxyAgent(),ua='ChatGPT-User; personal Elden Ring reference archive';const rr=await fetch('https://namu.wiki/robots.txt',{dispatcher:agent,headers:{'User-Agent':ua}});if(!rr.ok)throw Error('robots unavailable');const robots=robotsParser('https://namu.wiki/robots.txt',await rr.text());
const entries=buildDataset().filter(e=>['bosses','npcs','locations','talismans'].includes(e.category)&&!e.translationPending);const links=new Map<string,string>();
for(const page of ['보스','등장인물','지역']){const url='https://namu.wiki/w/'+encodeURIComponent('엘든 링/'+page);if(robots.isAllowed(url,'ChatGPT-User')===false)continue;const response=await fetch(url,{dispatcher:agent,headers:{'User-Agent':ua},signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('Index unavailable '+response.status);const $=cheerio.load(await response.text());$('a.wiki-link-internal[href^="/w/"]').each((_,a)=>{const title=$(a).attr('title');if(title)links.set(title,new URL($(a).attr('href')!,'https://namu.wiki').href);});await new Promise(r=>setTimeout(r,1200));}
const rows:any[]=fs.existsSync('data/enrichment/characters.json')?JSON.parse(fs.readFileSync('data/enrichment/characters.json','utf8')):[],images:any[]=[],report:any[]=[];
for(const e of entries){const url=links.get(e.nameKo);if(!url||robots.isAllowed(url,'ChatGPT-User')===false)continue;try{const response=await fetch(url,{dispatcher:agent,headers:{'User-Agent':ua},signal:AbortSignal.timeout(30000)});if(response.status===403||response.status===429){report.push({url,status:response.status});break;}if(!response.ok){report.push({url,status:response.status});continue;}const html=await response.text();const $=cheerio.load(html);$('.wiki-heading-content .wiki-paragraph').first();const imagesIn=$('img').filter((_,img)=>{const alt=$(img).attr('alt')??'',src=$(img).attr('src')??'';return src.startsWith('//i.namu.wiki/')&&(alt.includes('엘든')||alt.includes(e.nameKo)||alt.toLowerCase().includes(e.nameEn.toLowerCase()));});const img=imagesIn.first().attr('src');const details:Record<string,unknown>={};
// Only small label/value facts; never paragraphs or item-description quotations.
const allowed:Record<string,string>={'체력':'hp','HP':'hp','보상':'rewards','드롭':'drops','드랍':'drops','룬':'runes','등장 지역':'region','위치':'location','중량':'weight','무게':'weight','강인도':'poise'};
$('table.wiki-table tr').each((_,tr)=>{const cells=$(tr).children('td,th');if(cells.length!==2)return;const label=cells.eq(0).text().trim(),v=cells.eq(1).text().trim();if(allowed[label]&&v&&v.length<180)details[allowed[label]]=v;});
let imageUrl:string|undefined,assetId:string|undefined;if(img){imageUrl=new URL(img,'https://namu.wiki').href;assetId='asset-'+crypto.createHash('sha256').update(imageUrl).digest('hex').slice(0,32);images.push({id:assetId,url:imageUrl,source:url,kind:e.category==='locations'?'location':'portrait',rights:'게임/위키 이미지: 개인용 로컬 캐시. 출처에 귀속. 재배포 라이선스 미확인.'});details.assetId=assetId;}
const relatedNames:any[]=[];
const raw={id:e.id,nameKo:e.nameKo,nameEn:e.nameEn,category:e.category,content_type:e.content_type,imageUrl,imageSource:imageUrl?url:undefined,details,relatedNames:relatedNames.slice(0,70),sources:[{title:'나무위키 · 인물·지역 정형 정보',url,checkedAt:new Date().toISOString(),note:'짧은 표 사실과 이미지 출처만 추출. 다중 회차 체력·내성은 원문 확인 필요. 독립 검증 아님.'}]};assertAllowed(raw);rows.push(raw);report.push({url,status:'ok',image:!!imageUrl,facts:Object.keys(details).length});console.log(e.nameKo,!!imageUrl,Object.keys(details).length);}catch(err){report.push({url,status:String(err)});}await new Promise(r=>setTimeout(r,1200));}
fs.writeFileSync('data/enrichment/characters.json',JSON.stringify([...new Map(rows.map(r=>[r.id,r])).values()],null,2)+'\n');fs.writeFileSync('data/enrichment/characters-report.json',JSON.stringify(report,null,2)+'\n');const assets=JSON.parse(fs.readFileSync('data/assets.json','utf8'));fs.writeFileSync('data/assets.json',JSON.stringify([...new Map([...assets,...images].map(a=>[a.id,a])).values()],null,2)+'\n');console.log({documents:rows.length,images:images.length});await agent.destroy();
