import fs from 'node:fs';
import * as cheerio from 'cheerio';
import {buildDataset} from './dataset';
import {normalize,slug} from '../lib/catalog';
const all=buildDataset(),index=new Map(all.map(e=>[normalize(e.nameEn),e]));const rows:any[]=fs.existsSync('data/enrichment/locations.json')?JSON.parse(fs.readFileSync('data/enrichment/locations.json','utf8')):[],assets=JSON.parse(fs.readFileSync('data/assets.json','utf8'));const checkedAt=new Date().toISOString();
const pages=[['Gael Tunnel','wiki-gael.html'],['Limgrave','wiki-limgrave.html'],['Gravesite Plain','wiki-gravesite.html'],['Moonveil','wikigg.txt']];
const key:Record<string,string>={type:'type',region:'region',weight:'weight',skills:'skill',fp_cost:'fpCost',effects:'effect',bosses:'bosses',boss:'boss',location:'location'};
for(const [name,file] of pages){const e=index.get(normalize(name));if(!e||!fs.existsSync('/tmp/er-research/'+file))continue;const $=cheerio.load(fs.readFileSync('/tmp/er-research/'+file,'utf8'));const source='https://eldenring.wiki.gg/wiki/'+name.replaceAll(' ','_');const details:Record<string,unknown>={},relatedNames:any[]=[];$('.portable-infobox [data-source]').each((_,node)=>{const field=$(node).attr('data-source')!;if(key[field]){const value=$(node).find('.pi-data-value').text().trim();if(value&&value.length<350)details[key[field]]=field==='weight'?Number(value):value;}});
let heading='';$('.mw-parser-output').children().each((_,node)=>{if(/^h[23]$/i.test(node.tagName))heading=$(node).text().replace('[edit]','').trim();if(!['Sites of Grace','NPCs','Bosses','Notable Loot','Dungeons','Locations','Sub-Regions','Landmarks'].includes(heading))return;$(node).find('a[href^="/wiki/"]').each((_,a)=>{const n=$(a).attr('title');if(!n||!index.has(normalize(n)))return;const label=heading==='Notable Loot'?'주요 아이템':heading==='Bosses'?'보스':heading==='NPCs'?'NPC':heading==='Sites of Grace'?'축복':'지역·던전';if(!relatedNames.some(r=>r.name===n&&r.label===label))relatedNames.push({name:n,label});});});
rows.push({id:e.id,nameKo:e.nameKo,nameEn:e.nameEn,category:e.category,content_type:e.content_type,details,relatedNames:relatedNames.slice(0,90),sources:[{title:'Eldenpedia · 위치와 연관 문서',url:source,checkedAt,note:'이전에 정상 열람한 공개 HTML에서 기본 정보와 관련 장소 목록만 추출. 설명문 복사 없음.'}]});}
const routes:Record<string,string>={'Gael Tunnel':'케일리드 서쪽 썩은 자의 오두막 남쪽에서 갱도 입구로 들어갑니다. 수직 통로의 발판을 따라 내려가세요. 림그레이브 쪽 후문은 처음에는 안쪽에서만 열 수 있습니다. 갱도 보스 용암토룡을 처치하면 명도 월은을 얻습니다.','Gravesite Plain':'본편에서 별 부수는 라단과 피의 군주 모그를 처치한 뒤, 모그윈 왕조의 묘 최하층의 고치에 있는 손을 조사해 진입합니다. 처음에는 묘지 평원 지도를 확보하고 세 갈래의 십자로를 기준으로 진행하세요.'};for(const row of rows)if(routes[row.nameEn])row.details.navigation=routes[row.nameEn];
const maps=[{id:'lands-between',nameKo:'틈새의 땅 지도',nameEn:'Lands Between Map',content_type:'base_game',url:'https://raw.githubusercontent.com/F3T1W/EldenTracker/5ed26ce13922d151a64e7d8118a2e6adc8c416cf/Assets/FullMap.png',source:'https://github.com/F3T1W/EldenTracker',file:'Assets/FullMap.png'}, {id:'underground',nameKo:'지하세계 지도',nameEn:'Underground Map',content_type:'base_game',url:'https://raw.githubusercontent.com/elpwc/EldenRingOnlineMap/9659e35e0ff67dd676f878aef07665e8047f35e2/mapDivider/underground.png',source:'https://github.com/elpwc/EldenRingOnlineMap',file:'mapDivider/underground.png'}, {id:'realm-of-shadow',nameKo:'그림자의 땅 지도',nameEn:'Realm of Shadow Map',content_type:'shadow_of_the_erdtree',url:'https://raw.githubusercontent.com/elpwc/EldenRingOnlineMap/9659e35e0ff67dd676f878aef07665e8047f35e2/mapDivider/dlc1.png',source:'https://github.com/elpwc/EldenRingOnlineMap',file:'mapDivider/dlc1.png'}];
// These independently published full map files contain in-game labels. No inferred marker coordinates.
for(const m of maps){const assetId='map-'+m.id;assets.push({id:assetId,url:m.url,source:m.source,kind:'map',content_type:m.content_type,rights:'게임 지도 이미지: FromSoftware / Bandai Namco. 공개 커뮤니티 지도 저장소를 참조한 개인용 캐시. 코드 라이선스는 게임 이미지 재배포 허가와 별개입니다.'});rows.push({id:'maps-'+m.id,nameKo:m.nameKo,nameEn:m.nameEn,category:'maps',content_type:m.content_type,imageUrl:m.url,imageSource:m.source,details:{assetId,navigation:'지도 화면에서 확대·이동하거나 개인 위치 마커를 기록할 수 있습니다.'},sources:[{title:'공개 커뮤니티 지도 원본',url:m.source,checkedAt,note:m.file+' · 개인 참조용. 원본 이미지의 게임 저작권은 해당 권리자에게 있습니다.'}]});}
fs.writeFileSync('data/enrichment/locations.json',JSON.stringify([...new Map(rows.map(r=>[r.id,r])).values()],null,2)+'\n');fs.writeFileSync('data/assets.json',JSON.stringify([...new Map(assets.map((r:any)=>[r.id,r])).values()],null,2)+'\n');console.log({documents:rows.length,relationships:rows.reduce((n,r)=>n+(r.relatedNames?.length??0),0),assets:assets.length});
